---
 # tasks file for nginx
 
- name: 'Install required packages'
  apt:
    name: 'nginx'
    state: 'present'
    update_cache: true
  become: true
- name: 'Deploy nginx config file'
  template:
    src: 'wordpress'
    dest: '/etc/nginx/sites-available/wordpress'
  become: true
  notify: 'Restart nginx'
- name: 'Remove default nginx config'
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: 'absent'
  become: true
- name: 'Create symlink for wordpress'
  file:
    force: true
    src: '/etc/nginx/sites-available/wordpress'
    dest: '/etc/nginx/sites-enabled/wordpress'
    state: 'link'
  become: true


